<a href="https://colab.research.google.com/github/Nileshsri2022/ml-campusx/blob/main/day26-ordinal-encoding/day26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('customer.csv')

In [6]:
df.sample(5)

age  gender   review education purchased
24   16  Female  Average        PG       Yes
48   39  Female     Good        UG       Yes
21   32    Male  Average        PG        No
4    16  Female  Average        UG        No
32   92    Male  Average        UG       Yes

In [7]:
df = df.iloc[:,2:]

In [8]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [13]:
 X_train

review education
24  Average        PG
28     Poor    School
40     Good    School
46     Poor        PG
30  Average        UG
42     Good        PG
33     Good        PG
21  Average        PG
27     Poor        PG
20  Average    School
4   Average        UG
5   Average    School
14     Poor        PG
39     Poor        PG
10     Good        UG
8   Average        UG
25     Good    School
31     Poor    School
32  Average        UG
7      Poor    School
48     Good        UG
43     Poor        PG
1      Poor        UG
34  Average    School
41     Good        PG
44  Average        UG
18     Good    School
22     Poor        PG
13  Average    School
11     Good        UG
3      Good        PG
17     Poor        UG
35     Poor    School
19     Poor        PG
36     Good        UG
38     Good    School
2      Good        PG
9      Good        UG
0   Average    School
15     Poor        UG

In [14]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [15]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [16]:
X_train = oe.transform(X_train)

In [17]:
X_train

array([[1., 2.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [1., 2.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [1., 0.],
       [0., 1.]])

In [18]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [19]:
X_train

array([[1., 2.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [1., 2.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [1., 0.],
       [0., 1.]])

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
le = LabelEncoder()

In [22]:
le.fit(y_train)

LabelEncoder()

In [23]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [24]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [25]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0])